version: 2.1
orbs:
  node: circleci/node@4.5.1
workflows:
    example-workflow:
      jobs:
        - node/test:
            override-ci-command: npm ci 
            cache-version: v1 
            run-command: npm run test 

  